name = "wa-worker-d1"
compatibility_date = "2025-05-01"
main = "worker.js"
compatibility_flags = ["nodejs_compat"]

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "wa_sender_db"
database_id = "2eeeb175-c7c8-4e96-ab6a-b3a63a591008"

# Environment variables
[vars]
NODE_ENV = "production"